name: Auto Update Game Every 3 Minutes

on:
  schedule:
    - cron: "*/3 * * * *"  # every 3 minutes
  workflow_dispatch:

jobs:
  update-game:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Run updateGame.js
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm install
        node updateGame.js
